kind: Deployment
apiVersion: apps/v1
metadata:
  name: rest-app-deployment
  labels:
    app: rest-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: ilovehardrock/rest-app
        ports:
          - containerPort: 8080
        env:
        - name: DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: music-player-configmap
              key: database_host
        command: ["java", "-jar", "-Dspring.profiles.active=mySql", "app.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: rest-app-secrvice
spec:
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080