version: "3.8"
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicPlayer
    volumes:
    - ./mySql_data:/var/lib/mysql

  rest-app:
    build: ../rest-app
    container_name: rest-app
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: always
    environment:
      DB_HOSTNAME: db
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--","java", "-jar", "-Dspring.profiles.active=mySql", "app.jar"]

  web-app:
    build: ../web-app
    container_name: web-app
    ports:
      - 8090:8090
    expose:
      - 8090
    restart: always
    environment:
      HOST_NAME: rest-app
    depends_on:
      - rest-app
    command: [ "./wait-for-it.sh", "rest-app:8080", "--","java", "-jar", "app.jar" ]

  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
    - 9090:9090
    expose:
      - 9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.5.3
    ports:
    - 3000:3000
    volumes:
    - ./grafana:/etc/grafana/provisioning

