version: "3.8"
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicPlayer
    volumes:
    - ./mySql_data:/var/lib/mysql

  rest-app:
    build: ../rest-app
    image: docker-rest-app
    container_name: rest-app
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_HOSTNAME: db
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--","java", "-jar", "-Dspring.profiles.active=mySql", "app.jar"]

  web-app:
    build: ../web-app
    image: docker-web-app
    container_name: web-app
    ports:
      - 8090:8090
    restart: always
    environment:
      HOST_NAME: rest-app
    depends_on:
      - rest-app
    command: [ "./wait-for-it.sh", "rest-app:8080", "--","java", "-jar", "app.jar" ]

