ALTER TABLE PLAYLIST_SONG DROP CONSTRAINT FK_PLAYLIST;
ALTER TABLE PLAYLIST_SONG DROP CONSTRAINT FK_SONG;
ALTER TABLE SONG DROP CONSTRAINT Unique_Names;

TRUNCATE TABLE PLAYLIST_SONG;
TRUNCATE TABLE PLAYLIST;
TRUNCATE TABLE SONG;

ALTER TABLE PLAYLIST_SONG ADD CONSTRAINT FK_PLAYLIST FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST (PLAYLIST_ID) ON DELETE CASCADE;
ALTER TABLE PLAYLIST_SONG ADD CONSTRAINT FK_SONG FOREIGN KEY (SONG_ID) REFERENCES SONG (SONG_ID) ON DELETE CASCADE;
ALTER TABLE SONG ADD CONSTRAINT Unique_Names UNIQUE (SINGER,TITTLE);
ALTER TABLE PLAYLIST ALTER COLUMN PLAYLIST_ID RESTART WITH 1;
ALTER TABLE SONG ALTER COLUMN SONG_ID RESTART WITH 1;
