global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'rest-app'
    metrics_path: /management/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - rest-app:8080

  - job_name: 'web-app'
    metrics_path: /management/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - web-app:8090
